#Author : Twinkle Joseph
version: '3'
services:
  smartforms-db:
    build: 
        context: ./../..
        dockerfile: db/Dockerfile-postgres
    image: postgres/smartworkflow
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_POSTGRES_DB}
    ports:
      - '${APP_DB_PORT}:5432'  
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
  services:
    build:
      context: ./../..
      dockerfile: api/Dockerfile
    ports:
      - '${API_PORT}:8080'
    environment:
      - DATABASE_URL=postgresql://${DB_POSTGRES_USER}:${DB_POSTGRES_PASSWORD}@db:5432/${DB_POSTGRES_DB}
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT=${KEYCLOAK_CLIENT}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_CLIENT_ADMIN=${KEYCLOAK_CLIENT_ADMIN}
      - KEYCLOAK_CLIENT_ADMIN_SECRET=${KEYCLOAK_CLIENT_ADMIN_SECRET}
  web-portal:
    build:
      context: ./../..
      dockerfile: web/webportal/Dockerfile
      args:
        - API_BASE_URL=http://localhost:${API_PORT}/
        - KEYCLOAK_URL=${KEYCLOAK_URL}
        - KEYCLOAK_REALM=${KEYCLOAK_REALM}
        - KEYCLOAK_CLIENT=${KEYCLOAK_CLIENT}
        - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    ports:
      - '${WEB_PORT}:8080'
    depends_on:
      - services
volumes:
  dbdata:
