#Author : Jaise Thomas
version: '3'
services:
  #Dependencies for orbeon server
  orbeon-db:
    build: 
        context: ./../..
        dockerfile: orbeon/Dockerfile-postgres
    image: postgres/orbeon
    restart: always
    environment:
      - POSTGRES_USER=${DB_ORBEON_USER}
      - POSTGRES_PASSWORD=${DB_ORBEON_PASSWORD}
      - POSTGRES_DB=${DB_ORBEON_DB}
    volumes:
      - "./orbeondata:/var/lib/postgresql/orbeon_data"  
    ports:
      - '${DB_ORBEON_PORT}:5432'  
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_ORBEON_USER}']
      interval: 10s
      timeout: 5s
      retries: 5  
  orbeon: 
    build: 
        context: ./../..
        dockerfile: orbeon/Dockerfile
        args:
            tag: "tag-release-2018.2.1-ce"
            build: "orbeon-2018.2.1.201902072242-CE"
            postgre_jdbc_version: "42.2.9"
    image: orbeon-ce
    environment:
      - JAVA_OPTS= -Ddb.url=orbeon-db -Ddb.port=${DB_ORBEON_PORT} -Ddb.database=${DB_ORBEON_DB} -Ddb.username=${DB_ORBEON_USER} -Ddb.password=${DB_ORBEON_PASSWORD}
    ports: 
      - "${ORBEON_PORT}:8080"
    depends_on:
      - orbeon-db        
volumes:
  dbdata:
