/*
PURPOSE: MANAGE SYSTEM GROUPS
*/
DROP TABLE FORMSET;
CREATE TABLE FORMSET(
   FORMSET_ID    INT NOT NULL,
   FORMSET_NAME    VARCHAR(100) NOT NULL,
   FORMSET_DESCRIPTION    VARCHAR(500) NULL,
   STATUS   VARCHAR(20) NOT NULL,
   COMMENTS VARCHAR(1000) NULL,
   CREATED_BY	VARCHAR(100) NOT NULL,
   CREATED_TS	TIMESTAMP NOT NULL,
   UPDATED_BY	VARCHAR(100) NOT NULL,
   UPDATED_TS	TIMESTAMP NOT NULL,
   PRIMARY KEY(FORMSET_ID)
);


/*
PURPOSE: FORM-FORMSET MAINTENANCE
FORM_LOCATION CAN BE EXTRACTED AS KEY/VALUE ENTITY "SMARTFORM_ATTRIBUTES".
*/

DROP TABLE WEBFORM;
CREATE TABLE WEBFORM(
   FORM_ID    INT NOT NULL,
   FORM_NAME    VARCHAR(100) NOT NULL,
   FORM_DESCRIPTION    VARCHAR(500) NULL,
   FORM_SOURCE   VARCHAR(100) NOT NULL,
   FORM_LOCATION    VARCHAR(1000) NOT NULL,
   FORMSET_ID    INT NOT NULL,
   STATUS   VARCHAR(20) NOT NULL,
   COMMENTS VARCHAR(1000) NULL,
   CREATED_BY	VARCHAR(100) NOT NULL,
   CREATED_TS	TIMESTAMP NOT NULL,
   UPDATED_BY	VARCHAR(100) NOT NULL,
   UPDATED_TS	TIMESTAMP NOT NULL,
   PRIMARY KEY(FORM_ID,FORMSET_ID),
   FOREIGN KEY (FORMSET_ID) REFERENCES FORMSET (FORMSET_ID)
);


/*
PURPOSE: ORCHESTRATION PROCESS MAINTENANCE
PROCESS_LOCATION CAN BE EXTRACTED AS KEY/VALUE ENTITY "WORK_PROCESS_ATTRIBUTES".
*/

DROP TABLE WORK_PROCESS;
CREATE TABLE WORK_PROCESS(
   PROCESS_ID    INT NOT NULL,
   PROCESS_NAME    VARCHAR(500) NOT NULL,
   PROCESS_DESCRIPTION    VARCHAR(1000) NULL,
   PROCESS_SOURCE   VARCHAR(100) NOT NULL,
   PROCESS_KEY    VARCHAR(1000) NOT NULL,
   CREATED_BY	VARCHAR(100) NOT NULL,
   STATUS   VARCHAR(20) NOT NULL,
   COMMENTS VARCHAR(1000) NULL,
   CREATED_TS	TIMESTAMP NOT NULL,
   UPDATED_BY	VARCHAR(100) NOT NULL,
   UPDATED_TS	TIMESTAMP NOT NULL,
   PRIMARY KEY(PROCESS_ID)
);


/*
PURPOSE: SUPER ADMIN MAPPING CONTROL ENTITY
*/

DROP TABLE SMARTFORM_PROCESS_MAPPER;
CREATE TABLE SMARTFORM_PROCESS_MAPPER(
   MAP_ID    INT NOT NULL,
   FORM_ID    INT NOT NULL,
   FORM_NAME    VARCHAR(100) NOT NULL,
   FORMSET_ID    INT NULL,
   FORMSET_NAME    VARCHAR(100) NOT NULL,
   PROCESS_ID   INT NOT NULL,
   PROCESS_NAME    VARCHAR(100) NOT NULL,
   STATUS   VARCHAR(20) NOT NULL,
   COMMENTS VARCHAR(1000) NULL,
   CREATED_BY	VARCHAR(100) NOT NULL,
   CREATED_TS	TIMESTAMP NOT NULL,
   UPDATED_BY	VARCHAR(100) NOT NULL,
   UPDATED_TS	TIMESTAMP NOT NULL,
   PRIMARY KEY(MAP_ID)
);

/*
PURPOSE: FORM PROCESS INSTANCES TRACKER
*/

DROP TABLE SMARTFORM_ORCHESTRATION;
CREATE TABLE SMARTFORM_ORCHESTRATION(
   SYSTEM_CORR_ID INT NOT NULL,
   MAP_ID    INT NOT NULL,
   USER_ID   VARCHAR(50) NOT NULL,
   PROCESS_INSTANCE_ID VARCHAR(100),
   PROCESS_REF_ID INT NULL,
   DATA_ID  VARCHAR(50) NOT NULL,
   STATUS   VARCHAR(50),
   PROCESS_OWNER_GROUP	VARCHAR(100),
   PROCESS_ATTRIBS VARCHAR(4000),
   CREATED_BY	VARCHAR(100),
   CREATED_TS	TIMESTAMP,
   UPDATED_BY	VARCHAR(100),
   UPDATED_TS	TIMESTAMP,
   PRIMARY KEY(SYSTEM_CORR_ID)
);



CREATE SEQUENCE seq_smartform_process_mapper INCREMENT 1
     MINVALUE 1 MAXVALUE 99999
	 	 
CREATE SEQUENCE seq_formset INCREMENT 1
     MINVALUE 1 MAXVALUE 99999
	 
CREATE SEQUENCE seq_smart_webform INCREMENT 1
     MINVALUE 1 MAXVALUE 99999
	 
CREATE SEQUENCE seq_work_process INCREMENT 1
     MINVALUE 1 MAXVALUE 99999

CREATE SEQUENCE seq_smartform_orchestration INCREMENT 1
     MINVALUE 1 MAXVALUE 99999